### ISSUE TITLE
Multirange Labeled Slider: get signal for when handler is changed by enter value

### ISSUE THREAD

**Issue by looninho** [napari/superqt#103]
Hi,
What is the signal when a handle value is changed by enter double-click on its label ?

**Comment by tlambert03** [comment]
`valueChanged`?  if that's not what you're looking for, tell me what you tried, and what behavior specifically you're looking for

**Comment by looninho** [comment]
Not `valueChanged` because  I want to prevent continuous emit value when I move the slider, I use `sliderReleased` for that. But sometime the value is not accurate by moving the mouse so why I need the enter signal.
