### ISSUE TITLE
Dragging the bar on range sliders causes a crash with PyQt6

### ISSUE THREAD

**Issue by sfhbarnett** [napari/superqt#107]
**Describe the bug**
Dragging the bar (as opposed to the handles at the end) causes a crash with PyQt6 (and not PyQt5) with the following message:

```Traceback (most recent call last):
  File "/Users/sbarnett/opt/anaconda3/envs/PyV2/lib/python3.9/site-packages/superqt/sliders/_generic_range_slider.py", line 149, in mouseMoveEvent
    delta = self._clickOffset - self._pixelPosToRangeValue(self._pick(ev.pos()))
AttributeError: 'QMouseEvent' object has no attribute 'pos'
```

Seemingly this is the result of a change in the Qt API https://stackoverflow.com/questions/67496362/qmouseevent-object-has-no-attribute-pos

A fix is to change ev.pos() to ev.position() on line 149 in _generic_range_slider.py. I'd do this and make a pull request but this breaks backwards compatibility with PyQt5 and I don't know how to maintain that (or if there's a way). 

**To Reproduce**
Run the labeled.py example script with PyQt6 and click and drag the bar of a slider

**Expected behavior**
Slider bar drags

**Screenshots**
Screenshots and GIFS are much appreciated when reporting visual bugs.

**Desktop (please complete the following information):**
 - Mac OS 12.4
 - PyQT 6
 - Python 3.10

**Comment by sfhbarnett** [comment]
Great thanks! I learned something new today

**Comment by Czaki** [comment]
close?
