### ISSUE TITLE
Python 3.10 TypeError on rangeChanged for QLabeledRangeSlider

### ISSUE THREAD

**Issue by andrewb435** [napari/superqt#115]
There seems to be some kind of type mismatch in expected signal values in the rangeChanged with Python 3.10. When loading a UI with a QLabeledRangeSlider, Python exits with code 134 and the message 'TypeError: rangeChanged(self, int, int).emit(): argument 1 has unexpected type 'float''

1. Create a python 3.10 environment
2. Import PyQT5 and superqt
3. Create a UI with a QLabeledRangeSlider

**Desktop (please complete the following information):**
 - Fedora 36 KDE
 - PyQT5
 - Python 3.10.6

**Comment by tlambert03** [comment]
can you tell me how you installed pyqt and exactly what version you have?

**Comment by andrewb435** [comment]
PyQT5 was installed both in an anaconda venv and via pip3 (root and user). I've tried PyQT5 5.15.2 and 5.15.7 with the same symptoms.

**Comment by gordon-n-stevenson** [comment]
I had the same issue -  which had the TypeError as above at setRange. Then added in the pull request of #111  which resolved.

``self.focaldepth_field = QLabeledRangeSlider(Qt.Orientation.Horizontal) ``
``self.focaldepth_field.setRange(0,80)   ``
``self.focaldepth_field.setValue(tuple(focaldepth_val))  ``

**Comment by tlambert03** [comment]
thanks @gordon-n-stevenson  ... just waiting for a response to my request for a test there, and then can merge it
