### ISSUE TITLE
With PyQt6 & QRangeSlider "Must construct a QApplication before a QWidget"

### ISSUE THREAD

**Issue by xxxxme** [napari/superqt#36]
With PyQt6, Python core dumps "QWidget: Must construct a QApplication before a QWidget" when trying to use QRangeSlider.  This doesn't happen with PyQt5.

```#!/usr/bin/env python

import sys
from PyQt6 import QtWidgets
from superqt import QRangeSlider

class Main(QtWidgets.QMainWindow):
   def __init__(self):
      super().__init__()

      slider = QRangeSlider()

app = QtWidgets.QApplication(sys.argv)
mainwindow = Main()
mainwindow.show()
sys.exit(app.exec())
```
>QWidget: Must construct a QApplication before a QWidget

**Comment by tlambert03** [comment]
hmmm, I don't get this error when I run your script.  Can you print out your full environment with `conda list` or `pip list`?  

do you possibly have multiple Qt backends installed?  we can still potentially fix it, but I need to be able to reproduce it first

**Comment by tlambert03** [comment]
update: I just installed both pyqt5 and pyqt6 in the same environment and was able to reproduce

**Comment by tlambert03** [comment]
#34 fixes this issue when you have multiple Qt backends installed ... so will merge that.

**Comment by tlambert03** [comment]
should be fixed on main
