### ISSUE TITLE
How to setStyleSheet on second handle and groove

### ISSUE THREAD

**Issue by Gaalee** [napari/superqt#56]
Hi, i'm trying to use your QLabeledRangeSlider with PySide6 but setStyleSheet doesn't work for most of the things you can edit from QSlider class.

I tried to do 
```
self.range_slider = QLabeledRangeSlider(Qt.Horizontal)
QSS = """
   QSlider::groove:horizontal {
       border: 1px solid #999999;
       height: 8px; 
       background-color: green;
       margin: 2px 0;
   }
    QSlider::handle {
        background-color: red;
        height: 20px;
        width: 20px;
        border-radius: 10px;
   }
self.range_slider.setStyleSheet(QSS)
"""
```
But the only thing working is the handle being red. How can i style the second handle and the groove using the QLabeledRangeSilder widget ? Thanks.

**Comment by Gaalee** [comment]
Never mind its the same problem explain here #35 It work without any background-color on the frame.

**Comment by tlambert03** [comment]
thanks for the comment!  will close in favor of that issue
