### ISSUE TITLE
qtrangeslider has multiple slider controls that are either faded or non-functional

### ISSUE THREAD

**Issue by sfhbarnett** [napari/superqt#66]
**Describe the bug**
The qtrangeslider doesn't display properly. The range controls appear faded and there is a non-faded unmovable control at the bottom (screenshot below).

This code produces the error:
```
import sys
from PyQt5 import QtCore, QtWidgets
from qtrangeslider import QRangeSlider


class MainWindow(QtWidgets.QMainWindow):

    def __init__(self, *args, **kwargs):
        super(MainWindow, self).__init__(*args, **kwargs)

        vlayout2 = QtWidgets.QHBoxLayout()
        self.qtr = QRangeSlider(QtCore.Qt.Orientation.Vertical)
        self.qtr.setValue((11, 33))
        vlayout2.addWidget(self.qtr)
        widget = QtWidgets.QWidget()
        widget.setLayout(vlayout2)
        self.setCentralWidget(widget)

def main():
    if not QtWidgets.QApplication.instance():
        app = QtWidgets.QApplication(sys.argv)
    else:
        app = QtWidgets.QApplication.instance()
    app.setQuitOnLastWindowClosed(True)
    main = MainWindow()
    main.show()
    sys.exit(app.exec_())

if __name__ == '__main__':
    m = main()
```

**Expected behavior**
normal slider behaviour

**Screenshots**
<img width="408" alt="image" src="https://user-images.githubusercontent.com/45679976/153954223-32b4253d-df7d-4956-abe0-b0a153ff80b3.png">

**Desktop (please complete the following information):**
 - MacOS 12.1
 - PyQT 5.9.2, qtrangeslider 0.1.5
 - Python version 3.9

**Comment by tlambert03** [comment]
Thanks, the minimim supported version of Qt is 5.11, can you try updating pyqt5?

**Comment by tlambert03** [comment]
also, it looks like you're actually using `qtrangeslider` instead of `superqt`?  Please note that `qtrangeslider` is archived (and unmaintained)... use `from superqt import QRangeSlider` instead

**Comment by sfhbarnett** [comment]
I'm a bit embarrassed I did not check that! Updating fixed the issue and I also swapped to superqt. Thanks!
