### ISSUE TITLE
Collapsible shows black bars

### ISSUE THREAD

**Issue by MinmoTech** [napari/superqt#78]
**Describe the bug**
The Collapsible component from superqt shows a black bar instead of the arrow and the collapsible name.
![image](https://user-images.githubusercontent.com/25890405/163407231-698b1a85-53e6-4586-8abc-7b2cbb40f6b8.png)

**To Reproduce**
Code resulting in the above screenshot is hosted here: https://github.com/MinmoTech/collapsible-test
It is simply the example from this repository.

**Expected behavior**
There should be no black bars, the collapsible name and arrow should show normally.
Similar to this image in the original proposal:
![image](https://user-images.githubusercontent.com/25890405/163407724-61f6463f-85cf-434a-a2dc-93b73aab131e.png)

**Desktop (please complete the following information):**
 - Archlinux
 - Tested with PyQt5 and PySide6
 - Python 3.10
 - superqt version: 0.3.1

**Comment by MinmoTech** [comment]
@MosGeo Pinging you since you worked on the implementation of this :)

**Comment by MosGeo** [comment]
At first glance, I think something went horribly wrong with the arrow character that is used. It is probably not available in the default Linux font used. I have not tested it on Linux. 

Is it functioning (just a visual glitch?)

**Comment by MinmoTech** [comment]
Sorry, I should have mentioned that.
I works as it's supposed to, it's just a visual glitch :)

**Comment by MosGeo** [comment]
The current implementation uses symbols for arrows. Can you display this arrow correctly in arch Linux [https://www.fileformat.info/info/unicode/char/25b2/index.htm](https://www.fileformat.info/info/unicode/char/25b2/index.htm)

**Comment by MinmoTech** [comment]
It seems it is able to show the arrow by itself when used in a QLabel:
![image](https://user-images.githubusercontent.com/25890405/163693329-f92cfc48-439b-42e0-b7c0-411437e798e3.png)


Code i used:
```python
from qtpy.QtWidgets import QApplication, QLabel, QPushButton

from superqt import QCollapsible

app = QApplication([])


collapsible = QCollapsible("Advanced analysis")
collapsible.addWidget(QLabel("This is the inside of the collapsible frame"))
for i in range(10):
    collapsible.addWidget(QPushButton(f"Content button {i + 1}"))

arrowLable = QLabel("▲")
collapsible.addWidget(arrowLable)

collapsible.expand(animate=False)
collapsible.show()
app.exec_()
```

**Comment by MinmoTech** [comment]
I might have found the issue, I think it's the `transparent` part of the css:
```python
        self._toggle_btn.setStyleSheet("text-align: left; background: transparent;")
```
With that css:
![image](https://user-images.githubusercontent.com/25890405/163693470-441f16fc-05c8-4802-a4b4-092cdefe05df.png)


Removing the transparent part:
```python
        self._toggle_btn.setStyleSheet("text-align: left;")
```
![image](https://user-images.githubusercontent.com/25890405/163693455-660f8587-f634-4ecc-bdd6-448a1498bdd8.png)

**Comment by MinmoTech** [comment]
@MosGeo I made a PR that fixes the issue, could you look at it if it works for what you had in mind for the component? :)
