### ISSUE TITLE
[Proposal] Proper Documentation and Website

### ISSUE THREAD

**Issue by MosGeo** [napari/superqt#92]
As this library grows, it would be good to provide documentation on usage. If the proper infrastructure/base for documentation is added, contributors (e.g., me) can add documentations/tutorials as new features/widgets are added. In addition, more users and contributors will come around to the repo.

I don't have much experience with documentation. I started playing to sphinx for one of my side projects but didn't get to actually go deep into it yet. So having the initial structure created by more experienced person would be better. Slowly, we can start to populate the pages.

**Comment by tlambert03** [comment]
yep, we need docs.  See also #15.
